# Dictionary of major markets and their top stocks (~100 per market where applicable)

MARKETS = {
    "US - Tech (NASDAQ 100)": [
        {"ticker": "AAPL", "name": "Apple Inc."},
        {"ticker": "MSFT", "name": "Microsoft Corp."},
        {"ticker": "NVDA", "name": "NVIDIA Corp."},
        {"ticker": "GOOGL", "name": "Alphabet Inc. (Class A)"},
        {"ticker": "GOOG", "name": "Alphabet Inc. (Class C)"},
        {"ticker": "AMZN", "name": "Amazon.com Inc."},
        {"ticker": "META", "name": "Meta Platforms Inc."},
        {"ticker": "TSLA", "name": "Tesla Inc."},
        {"ticker": "AVGO", "name": "Broadcom Inc."},
        {"ticker": "ASML", "name": "ASML Holding"},
        {"ticker": "COST", "name": "Costco Wholesale"},
        {"ticker": "PEP", "name": "PepsiCo Inc."},
        {"ticker": "CSCO", "name": "Cisco Systems"},
        {"ticker": "TMUS", "name": "T-Mobile US"},
        {"ticker": "ADBE", "name": "Adobe Inc."},
        {"ticker": "TXN", "name": "Texas Instruments"},
        {"ticker": "CMCSA", "name": "Comcast Corp"},
        {"ticker": "AMD", "name": "Advanced Micro Devices"},
        {"ticker": "QCOM", "name": "Qualcomm Inc."},
        {"ticker": "NFLX", "name": "Netflix Inc."},
        {"ticker": "INTC", "name": "Intel Corp."},
        {"ticker": "AMGN", "name": "Amgen Inc."},
        {"ticker": "HON", "name": "Honeywell Int."},
        {"ticker": "INTU", "name": "Intuit Inc."},
        {"ticker": "SBUX", "name": "Starbucks Corp."},
        {"ticker": "BKNG", "name": "Booking Holdings"},
        {"ticker": "GILD", "name": "Gilead Sciences"},
        {"ticker": "ISRG", "name": "Intuitive Surgical"},
        {"ticker": "MDLZ", "name": "Mondelez Int."},
        {"ticker": "ADP", "name": "Automatic Data Proc."},
        {"ticker": "LRCX", "name": "Lam Research"},
        {"ticker": "REGN", "name": "Regeneron Pharma"},
        {"ticker": "VRTX", "name": "Vertex Pharma"},
        {"ticker": "PYPL", "name": "PayPal Holdings"},
        {"ticker": "MU", "name": "Micron Technology"},
        {"ticker": "ADI", "name": "Analog Devices"},
        {"ticker": "MELI", "name": "MercadoLibre"},
        {"ticker": "CSX", "name": "CSX Corp."},
        {"ticker": "KLAC", "name": "KLA Corp."},
        {"ticker": "PANW", "name": "Palo Alto Networks"},
        {"ticker": "SNPS", "name": "Synopsys Inc."},
        {"ticker": "CDNS", "name": "Cadence Design Sys."},
        {"ticker": "CHTR", "name": "Charter Comm."},
        {"ticker": "MAR", "name": "Marriott Int."},
        {"ticker": "ABNB", "name": "Airbnb Inc."},
        {"ticker": "MNST", "name": "Monster Beverage"},
        {"ticker": "ORLY", "name": "O'Reilly Automotive"},
        {"ticker": "LULU", "name": "Lululemon Athletica"},
        {"ticker": "NXPI", "name": "NXP Semiconductors"},
        {"ticker": "CRWD", "name": "CrowdStrike Holdings"},
        {"ticker": "MRVL", "name": "Marvell Technology"},
        {"ticker": "WDAY", "name": "Workday Inc."},
        {"ticker": "CTAS", "name": "Cintas Corp."},
        {"ticker": "DXCM", "name": "DexCom Inc."},
        {"ticker": "PCAR", "name": "PACCAR Inc."},
        {"ticker": "FTNT", "name": "Fortinet Inc."},
        {"ticker": "MCHP", "name": "Microchip Tech."},
        {"ticker": "KDP", "name": "Keurig Dr Pepper"},
        {"ticker": "PAYX", "name": "Paychex Inc."},
        {"ticker": "IDXX", "name": "IDEXX Laboratories"},
        {"ticker": "AEP", "name": "American Electric"},
        {"ticker": "EXC", "name": "Exelon Corp."},
        {"ticker": "AZN", "name": "AstraZeneca"},
        {"ticker": "BIIB", "name": "Biogen Inc."},
        {"ticker": "EA", "name": "Electronic Arts"},
        {"ticker": "XEL", "name": "Xcel Energy"},
        {"ticker": "ROST", "name": "Ross Stores"},
        {"ticker": "DLTR", "name": "Dollar Tree"},
        {"ticker": "FAST", "name": "Fastenal Co."},
        {"ticker": "WBA", "name": "Walgreens Boots"},
        {"ticker": "KHC", "name": "Kraft Heinz"},
        {"ticker": "ODFL", "name": "Old Dominion Freight"},
        {"ticker": "GEHC", "name": "GE HealthCare"},
        {"ticker": "BKR", "name": "Baker Hughes"},
        {"ticker": "VRSK", "name": "Verisk Analytics"},
        {"ticker": "CSGP", "name": "CoStar Group"},
        {"ticker": "ON", "name": "ON Semiconductor"},
        {"ticker": "GFS", "name": "GlobalFoundries"},
        {"ticker": "CDW", "name": "CDW Corp."},
        {"ticker": "ANSS", "name": "ANSYS Inc."},
        {"ticker": "TTD", "name": "The Trade Desk"},
        {"ticker": "TEAM", "name": "Atlassian"},
        {"ticker": "FANG", "name": "Diamondback Energy"},
        {"ticker": "DDOG", "name": "Datadog Inc."},
        {"ticker": "ZS", "name": "Zscaler Inc."},
        {"ticker": "ILMN", "name": "Illumina Inc."},
        {"ticker": "ALGN", "name": "Align Technology"},
        {"ticker": "EBAY", "name": "eBay Inc."},
        {"ticker": "ZM", "name": "Zoom Video Comm."},
        {"ticker": "SIRI", "name": "Sirius XM Holdings"},
        {"ticker": "ENPH", "name": "Enphase Energy"},
        {"ticker": "JD", "name": "JD.com Inc."},
        {"ticker": "PDD", "name": "PDD Holdings"},
        {"ticker": "LCID", "name": "Lucid Group"},
        {"ticker": "RIVN", "name": "Rivian Automotive"},
        {"ticker": "WBD", "name": "Warner Bros. Discovery"},
        {"ticker": "ARM", "name": "Arm Holdings"}
    ],
    "US - General (S&P 100+)": [
        {"ticker": "BRK-B", "name": "Berkshire Hathaway"},
        {"ticker": "LLY", "name": "Eli Lilly & Co"},
        {"ticker": "JPM", "name": "JPMorgan Chase"},
        {"ticker": "XOM", "name": "Exxon Mobil"},
        {"ticker": "UNH", "name": "UnitedHealth Group"},
        {"ticker": "V", "name": "Visa Inc."},
        {"ticker": "JNJ", "name": "Johnson & Johnson"},
        {"ticker": "PG", "name": "Procter & Gamble"},
        {"ticker": "MA", "name": "Mastercard Inc."},
        {"ticker": "HD", "name": "Home Depot"},
        {"ticker": "CVX", "name": "Chevron Corp."},
        {"ticker": "MRK", "name": "Merck & Co."},
        {"ticker": "ABBV", "name": "AbbVie Inc."},
        {"ticker": "KO", "name": "Coca-Cola Co."},
        {"ticker": "BAC", "name": "Bank of America"},
        {"ticker": "WMT", "name": "Walmart Inc."},
        {"ticker": "TMO", "name": "Thermo Fisher Sci."},
        {"ticker": "MCD", "name": "McDonald's Corp."},
        {"ticker": "CSCO", "name": "Cisco Systems"},
        {"ticker": "LIN", "name": "Linde plc"},
        {"ticker": "ACN", "name": "Accenture plc"},
        {"ticker": "ABT", "name": "Abbott Laboratories"},
        {"ticker": "DHR", "name": "Danaher Corp."},
        {"ticker": "DIS", "name": "Walt Disney Co."},
        {"ticker": "VZ", "name": "Verizon Comm."},
        {"ticker": "NEE", "name": "NextEra Energy"},
        {"ticker": "PM", "name": "Philip Morris Int."},
        {"ticker": "TXN", "name": "Texas Instruments"},
        {"ticker": "UPS", "name": "United Parcel Service"},
        {"ticker": "BMY", "name": "Bristol-Myers Squibb"},
        {"ticker": "WFC", "name": "Wells Fargo"},
        {"ticker": "RTX", "name": "RTX Corp."},
        {"ticker": "MS", "name": "Morgan Stanley"},
        {"ticker": "INTC", "name": "Intel Corp."},
        {"ticker": "CAT", "name": "Caterpillar Inc."},
        {"ticker": "BA", "name": "Boeing Co."},
        {"ticker": "HON", "name": "Honeywell Int."},
        {"ticker": "UNP", "name": "Union Pacific"},
        {"ticker": "GE", "name": "General Electric"},
        {"ticker": "IBM", "name": "IBM Corp."},
        {"ticker": "DE", "name": "Deere & Co."},
        {"ticker": "AMGN", "name": "Amgen Inc."},
        {"ticker": "SPGI", "name": "S&P Global"},
        {"ticker": "COP", "name": "ConocoPhillips"},
        {"ticker": "LOW", "name": "Lowe's Companies"},
        {"ticker": "GS", "name": "Goldman Sachs"},
        {"ticker": "PLD", "name": "Prologis Inc."},
        {"ticker": "LMT", "name": "Lockheed Martin"},
        {"ticker": "T", "name": "AT&T Inc."},
        {"ticker": "BLK", "name": "BlackRock Inc."},
        {"ticker": "SYK", "name": "Stryker Corp."},
        {"ticker": "AXP", "name": "American Express"},
        {"ticker": "ELV", "name": "Elevance Health"},
        {"ticker": "MDT", "name": "Medtronic plc"},
        {"ticker": "TJX", "name": "TJX Companies"},
        {"ticker": "GILD", "name": "Gilead Sciences"},
        {"ticker": "CVS", "name": "CVS Health"},
        {"ticker": "AMT", "name": "American Tower"},
        {"ticker": "ISRG", "name": "Intuitive Surgical"},
        {"ticker": "BKNG", "name": "Booking Holdings"},
        {"ticker": "ADI", "name": "Analog Devices"},
        {"ticker": "MDLZ", "name": "Mondelez Int."},
        {"ticker": "CI", "name": "Cigna Group"},
        {"ticker": "CB", "name": "Chubb Ltd"},
        {"ticker": "MMC", "name": "Marsh & McLennan"},
        {"ticker": "REGN", "name": "Regeneron Pharma"},
        {"ticker": "VRTX", "name": "Vertex Pharma"},
        {"ticker": "SLB", "name": "Schlumberger"},
        {"ticker": "MO", "name": "Altria Group"},
        {"ticker": "PGR", "name": "Progressive Corp"},
        {"ticker": "SO", "name": "Southern Co"},
        {"ticker": "TMUS", "name": "T-Mobile US"},
        {"ticker": "EOG", "name": "EOG Resources"},
        {"ticker": "BDX", "name": "Becton Dickinson"},
        {"ticker": "C", "name": "Citigroup Inc."},
        {"ticker": "NKE", "name": "Nike Inc."},
        {"ticker": "PYPL", "name": "PayPal Holdings"},
        {"ticker": "DUK", "name": "Duke Energy"},
        {"ticker": "USB", "name": "US Bancorp"},
        {"ticker": "PNC", "name": "PNC Financial"},
        {"ticker": "ZTS", "name": "Zoetis Inc."},
        {"ticker": "ITW", "name": "Illinois Tool Works"},
        {"ticker": "CL", "name": "Colgate-Palmolive"},
        {"ticker": "BSX", "name": "Boston Scientific"},
        {"ticker": "APD", "name": "Air Products"},
        {"ticker": "TGT", "name": "Target Corp."},
        {"ticker": "FDX", "name": "FedEx Corp."},
        {"ticker": "CSX", "name": "CSX Corp."},
        {"ticker": "SHW", "name": "Sherwin-Williams"},
        {"ticker": "MMM", "name": "3M Company"},
        {"ticker": "FCX", "name": "Freeport-McMoRan"},
        {"ticker": "MCK", "name": "McKesson Corp."},
        {"ticker": "AON", "name": "Aon plc"},
        {"ticker": "EMR", "name": "Emerson Electric"},
        {"ticker": "ORCL", "name": "Oracle Corp"}
    ],
    "UK - FTSE 100": [
        {"ticker": "SHEL.L", "name": "Shell plc"},
        {"ticker": "AZN.L", "name": "AstraZeneca"},
        {"ticker": "HSBA.L", "name": "HSBC Holdings"},
        {"ticker": "ULVR.L", "name": "Unilever"},
        {"ticker": "BP.L", "name": "BP plc"},
        {"ticker": "DGE.L", "name": "Diageo"},
        {"ticker": "RIO.L", "name": "Rio Tinto"},
        {"ticker": "GSK.L", "name": "GSK plc"},
        {"ticker": "GLEN.L", "name": "Glencore"},
        {"ticker": "REL.L", "name": "RELX"},
        {"ticker": "BATS.L", "name": "British American Tobacco"},
        {"ticker": "LSEG.L", "name": "London Stock Exchange"},
        {"ticker": "CNA.L", "name": "Centrica"},
        {"ticker": "NG.L", "name": "National Grid"},
        {"ticker": "AAL.L", "name": "Anglo American"},
        {"ticker": "LLOY.L", "name": "Lloyds Banking Group"},
        {"ticker": "BARC.L", "name": "Barclays"},
        {"ticker": "PRU.L", "name": "Prudential"},
        {"ticker": "VOD.L", "name": "Vodafone Group"},
        {"ticker": "RR.L", "name": "Rolls-Royce Holdings"},
        {"ticker": "CPG.L", "name": "Compass Group"},
        {"ticker": "BA.L", "name": "BAE Systems"},
        {"ticker": "EXPN.L", "name": "Experian"},
        {"ticker": "HLN.L", "name": "Haleon"},
        {"ticker": "FERG.L", "name": "Ferguson"},
        {"ticker": "SGE.L", "name": "Sage Group"},
        {"ticker": "NWG.L", "name": "NatWest Group"},
        {"ticker": "TSCO.L", "name": "Tesco"},
        {"ticker": "SSE.L", "name": "SSE plc"},
        {"ticker": "STAN.L", "name": "Standard Chartered"},
        {"ticker": "IMB.L", "name": "Imperial Brands"},
        {"ticker": "LGEN.L", "name": "Legal & General"},
        {"ticker": "ANTO.L", "name": "Antofagasta"},
        {"ticker": "AHT.L", "name": "Ashtead Group"},
        {"ticker": "FLTR.L", "name": "Flutter Entertainment"},
        {"ticker": "WPP.L", "name": "WPP plc"},
        {"ticker": "MNG.L", "name": "M&G plc"},
        {"ticker": "SVT.L", "name": "Severn Trent"},
        {"ticker": "UU.L", "name": "United Utilities"},
        {"ticker": "BT-A.L", "name": "BT Group"},
        {"ticker": "KGF.L", "name": "Kingfisher"},
        {"ticker": "SMIN.L", "name": "Smiths Group"},
        {"ticker": "PSON.L", "name": "Pearson"},
        {"ticker": "SBRY.L", "name": "Sainsbury's"},
        {"ticker": "LAND.L", "name": "Land Securities"},
        {"ticker": "BLND.L", "name": "British Land"},
        {"ticker": "RMV.L", "name": "Rightmove"},
        {"ticker": "AUTO.L", "name": "Auto Trader Group"},
        {"ticker": "WTB.L", "name": "Whitbread"},
        {"ticker": "IHG.L", "name": "InterContinental Hotels"},
        {"ticker": "NXT.L", "name": "Next plc"},
        {"ticker": "MKS.L", "name": "Marks & Spencer"},
        {"ticker": "JD.L", "name": "JD Sports Fashion"},
        {"ticker": "ABF.L", "name": "Assoc. British Foods"},
        {"ticker": "BDEV.L", "name": "Barratt Developments"},
        {"ticker": "TW.L", "name": "Taylor Wimpey"},
        {"ticker": "PSN.L", "name": "Persimmon"},
        {"ticker": "BKG.L", "name": "Berkeley Group"},
        {"ticker": "DCC.L", "name": "DCC plc"},
        {"ticker": "CRH.L", "name": "CRH plc"},
        {"ticker": "SMDS.L", "name": "Smith (DS)"},
        {"ticker": "MNDI.L", "name": "Mondi"},
        {"ticker": "SKG.L", "name": "Smurfit Kappa"},
        {"ticker": "SPX.L", "name": "Spirax-Sarco"},
        {"ticker": "HLMA.L", "name": "Halma"},
        {"ticker": "AV.L", "name": "Aviva"},
        {"ticker": "PHNX.L", "name": "Phoenix Group"},
        {"ticker": "SDR.L", "name": "Schroders"},
        {"ticker": "STJ.L", "name": "St. James's Place"},
        {"ticker": "III.L", "name": "3i Group"},
        {"ticker": "Hargreaves Lansdown", "name": "HL.L"},
        {"ticker": "ENT.L", "name": "Entain"},
        {"ticker": "IAG.L", "name": "Intl Airlines Group"},
        {"ticker": "EZJ.L", "name": "easyJet"},
        {"ticker": "OCDO.L", "name": "Ocado Group"},
        {"ticker": "RS1.L", "name": "RS Group"},
        {"ticker": "WEIR.L", "name": "Weir Group"},
        {"ticker": "IMI.L", "name": "IMI plc"},
        {"ticker": "BRBY.L", "name": "Burberry Group"},
        {"ticker": "CCH.L", "name": "Coca-Cola HBC"},
        {"ticker": "BNZL.L", "name": "Bunzl"},
        {"ticker": "INF.L", "name": "Informa"},
        {"ticker": "ITRK.L", "name": "Intertek Group"},
        {"ticker": "RKT.L", "name": "Reckitt Benckiser"},
        {"ticker": "SMT.L", "name": "Scottish Mortgage Inv"},
        {"ticker": "FTE.L", "name": "Fresnillo"},
        {"ticker": "EDV.L", "name": "Endeavour Mining"},
        {"ticker": "HIK.L", "name": "Hikma Pharmaceuticals"},
        {"ticker": "SN.L", "name": "Smith & Nephew"},
        {"ticker": "CPT.L", "name": "Croda International"},
        {"ticker": "JMAT.L", "name": "Johnson Matthey"},
        {"ticker": "KLR.L", "name": "Keller Group"},
        {"ticker": "DLG.L", "name": "Direct Line Group"}
    ],
    "Europe - Euro Stoxx 50+": [
        {"ticker": "MC.PA", "name": "LVMH Moet Hennessy"},
        {"ticker": "OR.PA", "name": "L'Oreal"},
        {"ticker": "RMS.PA", "name": "Hermes International"},
        {"ticker": "SAP.DE", "name": "SAP SE"},
        {"ticker": "SIE.DE", "name": "Siemens AG"},
        {"ticker": "TTE.PA", "name": "TotalEnergies"},
        {"ticker": "SAN.PA", "name": "Sanofi"},
        {"ticker": "ALV.DE", "name": "Allianz"},
        {"ticker": "AIR.PA", "name": "Airbus"},
        {"ticker": "IBE.MC", "name": "Iberdrola"},
        {"ticker": "DTE.DE", "name": "Deutsche Telekom"},
        {"ticker": "SU.PA", "name": "Schneider Electric"},
        {"ticker": "AI.PA", "name": "Air Liquide"},
        {"ticker": "EL.PA", "name": "EssilorLuxottica"},
        {"ticker": "BNP.PA", "name": "BNP Paribas"},
        {"ticker": "CS.PA", "name": "AXA"},
        {"ticker": "ITX.MC", "name": "Inditex"},
        {"ticker": "BAYN.DE", "name": "Bayer AG"},
        {"ticker": "MBG.DE", "name": "Mercedes-Benz Group"},
        {"ticker": "BMW.DE", "name": "BMW"},
        {"ticker": "VOW3.DE", "name": "Volkswagen (Pref)"},
        {"ticker": "BAS.DE", "name": "BASF"},
        {"ticker": "DPW.DE", "name": "Deutsche Post"},
        {"ticker": "MUV2.DE", "name": "Munich Re"},
        {"ticker": "IFX.DE", "name": "Infineon Technologies"},
        {"ticker": "AD.AS", "name": "Ahold Delhaize"},
        {"ticker": "INGA.AS", "name": "ING Group"},
        {"ticker": "ADYEN.AS", "name": "Adyen"},
        {"ticker": "PRX.AS", "name": "Prosus"},
        {"ticker": "KNEBV.HE", "name": "Kone"},
        {"ticker": "NOKIA.HE", "name": "Nokia"},
        {"ticker": "NDA-FI.HE", "name": "Nordea Bank"},
        {"ticker": "ENEL.MI", "name": "Enel"},
        {"ticker": "ISP.MI", "name": "Intesa Sanpaolo"},
        {"ticker": "UCG.MI", "name": "UniCredit"},
        {"ticker": "ENI.MI", "name": "Eni"},
        {"ticker": "STLAM.MI", "name": "Stellantis"},
        {"ticker": "FER.MI", "name": "Ferrari"},
        {"ticker": "RACE.MI", "name": "Ferrari (Dual)"},
        {"ticker": "G.MI", "name": "Generali"},
        {"ticker": "BBVA.MC", "name": "BBVA"},
        {"ticker": "SAN.MC", "name": "Banco Santander"},
        {"ticker": "TEF.MC", "name": "Telefonica"},
        {"ticker": "REP.MC", "name": "Repsol"},
        {"ticker": "AMS.MC", "name": "Amadeus IT Group"},
        {"ticker": "CFR.SW", "name": "Richemont"},
        {"ticker": "NESN.SW", "name": "Nestle"},
        {"ticker": "NOVN.SW", "name": "Novartis"},
        {"ticker": "ROG.SW", "name": "Roche Holding"},
        {"ticker": "ZURN.SW", "name": "Zurich Insurance"},
        {"ticker": "UBSG.SW", "name": "UBS Group"},
        {"ticker": "ABBN.SW", "name": "ABB Ltd"},
        {"ticker": "SIKA.SW", "name": "Sika"},
        {"ticker": "LQN.SW", "name": "Lonza Group"},
        {"ticker": "GIVN.SW", "name": "Givaudan"},
        {"ticker": "HOLN.SW", "name": "Holcim"},
        {"ticker": "SWISS.SW", "name": "Swiss Re"},
        {"ticker": "SCMN.SW", "name": "Swisscom"},
        {"ticker": "SGS.SW", "name": "SGS"},
        {"ticker": "PART.SW", "name": "Partners Group"},
        {"ticker": "NOVO-B.CO", "name": "Novo Nordisk"},
        {"ticker": "DSV.CO", "name": "DSV"},
        {"ticker": "VWS.CO", "name": "Vestas Wind Systems"},
        {"ticker": "ORSTED.CO", "name": "Orsted"},
        {"ticker": "MAERSK-B.CO", "name": "AP Moller Maersk"},
        {"ticker": "CARL-B.CO", "name": "Carlsberg"},
        {"ticker": "VOLV-B.ST", "name": "Volvo"},
        {"ticker": "ATCO-A.ST", "name": "Atlas Copco"},
        {"ticker": "ERIC-B.ST", "name": "Ericsson"},
        {"ticker": "HM-B.ST", "name": "H&M"},
        {"ticker": "SAND.ST", "name": "Sandvik"},
        {"ticker": "SEB-A.ST", "name": "SEB"},
        {"ticker": "SHB-A.ST", "name": "Svenska Handelsbanken"},
        {"ticker": "SWED-A.ST", "name": "Swedbank"},
        {"ticker": "TELIA.ST", "name": "Telia Company"},
        {"ticker": "ASSAB.ST", "name": "ASSA ABLOY"},
        {"ticker": "EQNR.OL", "name": "Equinor"},
        {"ticker": "DNB.OL", "name": "DNB Bank"},
        {"ticker": "NHY.OL", "name": "Norsk Hydro"},
        {"ticker": "TEL.OL", "name": "Telenor"},
        {"ticker": "YAR.OL", "name": "Yara International"},
        {"ticker": "MOWI.OL", "name": "Mowi"},
        {"ticker": "ORK.OL", "name": "Orkla"},
        {"ticker": "AKRBP.OL", "name": "Aker BP"},
        {"ticker": "TOM.OL", "name": "Tomra Systems"},
        {"ticker": "GJF.OL", "name": "Gjensidige Forsikring"}
    ],
    "Japan - Nikkei 225 Top": [
        {"ticker": "7203.T", "name": "Toyota Motor"},
        {"ticker": "6758.T", "name": "Sony Group"},
        {"ticker": "9984.T", "name": "SoftBank Group"},
        {"ticker": "6861.T", "name": "Keyence"},
        {"ticker": "8306.T", "name": "Mitsubishi UFJ"},
        {"ticker": "9983.T", "name": "Fast Retailing"},
        {"ticker": "6098.T", "name": "Recruit Holdings"},
        {"ticker": "4063.T", "name": "Shin-Etsu Chemical"},
        {"ticker": "9432.T", "name": "Nippon Telegraph & Tel"},
        {"ticker": "8035.T", "name": "Tokyo Electron"},
        {"ticker": "8316.T", "name": "Sumitomo Mitsui FG"},
        {"ticker": "8058.T", "name": "Mitsubishi Corp"},
        {"ticker": "8001.T", "name": "Itochu Corp"},
        {"ticker": "7974.T", "name": "Nintendo"},
        {"ticker": "4502.T", "name": "Takeda Pharma"},
        {"ticker": "7267.T", "name": "Honda Motor"},
        {"ticker": "6501.T", "name": "Hitachi"},
        {"ticker": "8411.T", "name": "Mizuho Financial"},
        {"ticker": "6367.T", "name": "Daikin Industries"},
        {"ticker": "4543.T", "name": "Terumo"},
        {"ticker": "7741.T", "name": "HOYA"},
        {"ticker": "6954.T", "name": "Fanuc"},
        {"ticker": "6273.T", "name": "SMC Corp"},
        {"ticker": "4452.T", "name": "Kao Corp"},
        {"ticker": "8031.T", "name": "Mitsui & Co"},
        {"ticker": "6902.T", "name": "Denso"},
        {"ticker": "4519.T", "name": "Chugai Pharma"},
        {"ticker": "6594.T", "name": "Nidec"},
        {"ticker": "8802.T", "name": "Mitsubishi Estate"},
        {"ticker": "4661.T", "name": "Oriental Land"},
        {"ticker": "4901.T", "name": "Fujifilm"},
        {"ticker": "8766.T", "name": "Tokio Marine"},
        {"ticker": "9433.T", "name": "KDDI"},
        {"ticker": "2914.T", "name": "Japan Tobacco"},
        {"ticker": "7201.T", "name": "Nissan Motor"},
        {"ticker": "5108.T", "name": "Bridgestone"},
        {"ticker": "7733.T", "name": "Olympus"},
        {"ticker": "6981.T", "name": "Murata Mfg"},
        {"ticker": "9434.T", "name": "SoftBank Corp"},
        {"ticker": "8801.T", "name": "Mitsui Fudosan"},
        {"ticker": "6702.T", "name": "Fujitsu"},
        {"ticker": "9020.T", "name": "JR East"},
        {"ticker": "9022.T", "name": "JR Central"},
        {"ticker": "6301.T", "name": "Komatsu"},
        {"ticker": "8002.T", "name": "Marubeni"},
        {"ticker": "9735.T", "name": "Secom"},
        {"ticker": "7270.T", "name": "Subaru"},
        {"ticker": "2413.T", "name": "M3 Inc"},
        {"ticker": "1925.T", "name": "Daiwa House"},
        {"ticker": "4568.T", "name": "Daiichi Sankyo"},
        {"ticker": "6752.T", "name": "Panasonic"},
        {"ticker": "4523.T", "name": "Eisai"},
        {"ticker": "7269.T", "name": "Suzuki Motor"},
        {"ticker": "4911.T", "name": "Shiseido"},
        {"ticker": "4503.T", "name": "Astellas Pharma"},
        {"ticker": "4507.T", "name": "Shionogi"},
        {"ticker": "2802.T", "name": "Ajinomoto"},
        {"ticker": "5401.T", "name": "Nippon Steel"},
        {"ticker": "6503.T", "name": "Mitsubishi Electric"},
        {"ticker": "2502.T", "name": "Asahi Group"},
        {"ticker": "2503.T", "name": "Kirin Holdings"},
        {"ticker": "9202.T", "name": "ANA Holdings"},
        {"ticker": "9101.T", "name": "NYK Line"},
        {"ticker": "9104.T", "name": "Mitsui OSK Lines"},
        {"ticker": "3402.T", "name": "Toray Industries"},
        {"ticker": "3407.T", "name": "Asahi Kasei"},
        {"ticker": "4188.T", "name": "Mitsubishi Chemical"},
        {"ticker": "6645.T", "name": "Omron"},
        {"ticker": "6971.T", "name": "Kyocera"},
        {"ticker": "7011.T", "name": "Mitsubishi Heavy Ind"},
        {"ticker": "7751.T", "name": "Canon"},
        {"ticker": "1928.T", "name": "Sekisui House"},
        {"ticker": "8604.T", "name": "Nomura Holdings"},
        {"ticker": "8725.T", "name": "MS&AD Insurance"},
        {"ticker": "8750.T", "name": "Dai-ichi Life"},
        {"ticker": "8630.T", "name": "Sompo Holdings"},
        {"ticker": "6586.T", "name": "Makita"},
        {"ticker": "6479.T", "name": "MinebeaMitsumi"},
        {"ticker": "5802.T", "name": "Sumitomo Electric"},
        {"ticker": "6920.T", "name": "Lasertec"},
        {"ticker": "6723.T", "name": "Renesas Electronics"},
        {"ticker": "4689.T", "name": "Z Holdings"},
        {"ticker": "4755.T", "name": "Rakuten"},
        {"ticker": "3382.T", "name": "Seven & i"},
        {"ticker": "8267.T", "name": "Aeon"},
        {"ticker": "2801.T", "name": "Kikkoman"},
        {"ticker": "2269.T", "name": "Meiji Holdings"},
        {"ticker": "9021.T", "name": "JR West"},
        {"ticker": "9009.T", "name": "Keisei Electric Railway"},
        {"ticker": "9007.T", "name": "Odakyu Electric Railway"},
        {"ticker": "9005.T", "name": "Tokyu Corp"},
        {"ticker": "8830.T", "name": "Sumitomo Realty"},
        {"ticker": "3092.T", "name": "ZOZO"},
        {"ticker": "4324.T", "name": "Dentsu Group"},
        {"ticker": "4578.T", "name": "Otsuka Holdings"},
        {"ticker": "4506.T", "name": "Sumitomo Pharma"},
        {"ticker": "4151.T", "name": "Kyowa Kirin"},
        {"ticker": "3659.T", "name": "Nexon"},
        {"ticker": "9613.T", "name": "NTT Data"},
        {"ticker": "9766.T", "name": "Konami"}
    ],
    "Crypto (Top 100)": [
        {"ticker": "BTC-USD", "name": "Bitcoin"},
        {"ticker": "ETH-USD", "name": "Ethereum"},
        {"ticker": "USDT-USD", "name": "Tether"},
        {"ticker": "BNB-USD", "name": "Binance Coin"},
        {"ticker": "SOL-USD", "name": "Solana"},
        {"ticker": "XRP-USD", "name": "XRP"},
        {"ticker": "USDC-USD", "name": "USDC"},
        {"ticker": "ADA-USD", "name": "Cardano"},
        {"ticker": "AVAX-USD", "name": "Avalanche"},
        {"ticker": "DOGE-USD", "name": "Dogecoin"},
        {"ticker": "TRX-USD", "name": "TRON"},
        {"ticker": "DOT-USD", "name": "Polkadot"},
        {"ticker": "LINK-USD", "name": "Chainlink"},
        {"ticker": "MATIC-USD", "name": "Polygon"},
        {"ticker": "TON-USD", "name": "Toncoin"},
        {"ticker": "SHIB-USD", "name": "Shiba Inu"},
        {"ticker": "LTC-USD", "name": "Litecoin"},
        {"ticker": "DAI-USD", "name": "Dai"},
        {"ticker": "BCH-USD", "name": "Bitcoin Cash"},
        {"ticker": "UNI-USD", "name": "Uniswap"},
        {"ticker": "ATOM-USD", "name": "Cosmos"},
        {"ticker": "LEO-USD", "name": "UNUS SED LEO"},
        {"ticker": "XLM-USD", "name": "Stellar"},
        {"ticker": "OKB-USD", "name": "OKB"},
        {"ticker": "ETC-USD", "name": "Ethereum Classic"},
        {"ticker": "INJ-USD", "name": "Injective"},
        {"ticker": "XMR-USD", "name": "Monero"},
        {"ticker": "FIL-USD", "name": "Filecoin"},
        {"ticker": "LDO-USD", "name": "Lido DAO"},
        {"ticker": "HBAR-USD", "name": "Hedera"},
        {"ticker": "ICP-USD", "name": "Internet Computer"},
        {"ticker": "APT-USD", "name": "Aptos"},
        {"ticker": "CRO-USD", "name": "Cronos"},
        {"ticker": "NEAR-USD", "name": "NEAR Protocol"},
        {"ticker": "VET-USD", "name": "VeChain"},
        {"ticker": "OP-USD", "name": "Optimism"},
        {"ticker": "MKR-USD", "name": "Maker"},
        {"ticker": "QNT-USD", "name": "Quant"},
        {"ticker": "AAVE-USD", "name": "Aave"},
        {"ticker": "GRT-USD", "name": "The Graph"},
        {"ticker": "ALGO-USD", "name": "Algorand"},
        {"ticker": "RNDR-USD", "name": "Render"},
        {"ticker": "STX-USD", "name": "Stacks"},
        {"ticker": "BSV-USD", "name": "Bitcoin SV"},
        {"ticker": "IMX-USD", "name": "Immutable"},
        {"ticker": "EGLD-USD", "name": "MultiversX"},
        {"ticker": "AXS-USD", "name": "Axie Infinity"},
        {"ticker": "SAND-USD", "name": "The Sandbox"},
        {"ticker": "THETA-USD", "name": "Theta Network"},
        {"ticker": "XTZ-USD", "name": "Tezos"},
        {"ticker": "MANA-USD", "name": "Decentraland"},
        {"ticker": "EOS-USD", "name": "EOS"},
        {"ticker": "FTM-USD", "name": "Fantom"},
        {"ticker": "SNX-USD", "name": "Synthetix"},
        {"ticker": "NEO-USD", "name": "Neo"},
        {"ticker": "FLOW-USD", "name": "Flow"},
        {"ticker": "KCS-USD", "name": "KuCoin Token"},
        {"ticker": "CFX-USD", "name": "Conflux"},
        {"ticker": "RPL-USD", "name": "Rocket Pool"},
        {"ticker": "CRV-USD", "name": "Curve DAO Token"},
        {"ticker": "KLAY-USD", "name": "Klaytn"},
        {"ticker": "GALA-USD", "name": "Gala"},
        {"ticker": "CHZ-USD", "name": "Chiliz"},
        {"ticker": "ZEC-USD", "name": "Zcash"},
        {"ticker": "IOTA-USD", "name": "IOTA"},
        {"ticker": "MINA-USD", "name": "Mina"},
        {"ticker": "FXS-USD", "name": "Frax Share"},
        {"ticker": "HT-USD", "name": "Huobi Token"},
        {"ticker": "BTT-USD", "name": "BitTorrent"},
        {"ticker": "CAKE-USD", "name": "PancakeSwap"},
        {"ticker": "XEC-USD", "name": "eCash"},
        {"ticker": "DASH-USD", "name": "Dash"},
        {"ticker": "MIOTA-USD", "name": "IOTA"},
        {"ticker": "AR-USD", "name": "Arweave"},
        {"ticker": "PAXG-USD", "name": "PAX Gold"},
        {"ticker": "TWT-USD", "name": "Trust Wallet Token"},
        {"ticker": "FEI-USD", "name": "Fei USD"},
        {"ticker": "KAVA-USD", "name": "Kava"},
        {"ticker": "LUNC-USD", "name": "Terra Classic"},
        {"ticker": "COMP-USD", "name": "Compound"},
        {"ticker": "ZIL-USD", "name": "Zilliqa"},
        {"ticker": "1INCH-USD", "name": "1inch Network"},
        {"ticker": "HOT-USD", "name": "Holo"},
        {"ticker": "RVN-USD", "name": "Ravencoin"},
        {"ticker": "NEXO-USD", "name": "Nexo"},
        {"ticker": "BAT-USD", "name": "Basic Attention Token"},
        {"ticker": "ENJ-USD", "name": "Enjin Coin"},
        {"ticker": "LRC-USD", "name": "Loopring"},
        {"ticker": "QTUM-USD", "name": "Qtum"},
        {"ticker": "YFI-USD", "name": "yearn.finance"},
        {"ticker": "CELO-USD", "name": "Celo"},
        {"ticker": "MASK-USD", "name": "Mask Network"},
        {"ticker": "GLM-USD", "name": "Golem"},
        {"ticker": "ANKR-USD", "name": "Ankr"},
        {"ticker": "JASMY-USD", "name": "JasmyCoin"},
        {"ticker": "SC-USD", "name": "Siacoin"},
        {"ticker": "ICX-USD", "name": "ICON"}
    ]
}

# New Sectors Dictionary
SECTORS = {
    "Technology": [
        {"ticker": "AAPL", "name": "Apple Inc."},
        {"ticker": "MSFT", "name": "Microsoft Corp."},
        {"ticker": "NVDA", "name": "NVIDIA Corp."},
        {"ticker": "GOOGL", "name": "Alphabet Inc."},
        {"ticker": "AMZN", "name": "Amazon.com Inc."},
        {"ticker": "META", "name": "Meta Platforms"},
        {"ticker": "AVGO", "name": "Broadcom Inc."},
        {"ticker": "CSCO", "name": "Cisco Systems"},
        {"ticker": "ADBE", "name": "Adobe Inc."},
        {"ticker": "CRM", "name": "Salesforce Inc."},
        {"ticker": "AMD", "name": "Advanced Micro Devices"},
        {"ticker": "INTC", "name": "Intel Corp."},
        {"ticker": "QCOM", "name": "Qualcomm Inc."},
        {"ticker": "IBM", "name": "IBM Corp."},
        {"ticker": "ORCL", "name": "Oracle Corp."},
        {"ticker": "TXN", "name": "Texas Instruments"},
        {"ticker": "NOW", "name": "ServiceNow"},
        {"ticker": "UBER", "name": "Uber Technologies"},
        {"ticker": "ABNB", "name": "Airbnb Inc."},
        {"ticker": "SAP.DE", "name": "SAP SE"}
    ],
    "Automotive (Cars)": [
        {"ticker": "TSLA", "name": "Tesla Inc."},
        {"ticker": "TM", "name": "Toyota Motor Corp"},
        {"ticker": "F", "name": "Ford Motor Co"},
        {"ticker": "GM", "name": "General Motors"},
        {"ticker": "STLA", "name": "Stellantis NV"},
        {"ticker": "HMC", "name": "Honda Motor Co"},
        {"ticker": "BMW.DE", "name": "BMW"},
        {"ticker": "VOW3.DE", "name": "Volkswagen"},
        {"ticker": "MBG.DE", "name": "Mercedes-Benz"},
        {"ticker": "RACE", "name": "Ferrari NV"},
        {"ticker": "LCID", "name": "Lucid Group"},
        {"ticker": "RIVN", "name": "Rivian Automotive"},
        {"ticker": "NIO", "name": "NIO Inc."},
        {"ticker": "XPEV", "name": "XPeng Inc."},
        {"ticker": "LI", "name": "Li Auto Inc."}
    ],
    "Finance & Banking": [
        {"ticker": "JPM", "name": "JPMorgan Chase"},
        {"ticker": "BAC", "name": "Bank of America"},
        {"ticker": "WFC", "name": "Wells Fargo"},
        {"ticker": "C", "name": "Citigroup"},
        {"ticker": "GS", "name": "Goldman Sachs"},
        {"ticker": "MS", "name": "Morgan Stanley"},
        {"ticker": "V", "name": "Visa Inc."},
        {"ticker": "MA", "name": "Mastercard"},
        {"ticker": "AXP", "name": "American Express"},
        {"ticker": "HSBC", "name": "HSBC Holdings"},
        {"ticker": "BLK", "name": "BlackRock"},
        {"ticker": "UBS", "name": "UBS Group"},
        {"ticker": "PYPL", "name": "PayPal"},
        {"ticker": "COIN", "name": "Coinbase Global"},
        {"ticker": "SCHW", "name": "Charles Schwab"}
    ],
    "Healthcare & Pharma": [
        {"ticker": "LLY", "name": "Eli Lilly"},
        {"ticker": "UNH", "name": "UnitedHealth Group"},
        {"ticker": "JNJ", "name": "Johnson & Johnson"},
        {"ticker": "MRK", "name": "Merck & Co."},
        {"ticker": "ABBV", "name": "AbbVie Inc."},
        {"ticker": "TMO", "name": "Thermo Fisher"},
        {"ticker": "NVS", "name": "Novartis"},
        {"ticker": "AZN", "name": "AstraZeneca"},
        {"ticker": "PFE", "name": "Pfizer Inc."},
        {"ticker": "AMGN", "name": "Amgen Inc."},
        {"ticker": "ISRG", "name": "Intuitive Surgical"},
        {"ticker": "CVS", "name": "CVS Health"},
        {"ticker": "ELV", "name": "Elevance Health"},
        {"ticker": "GILD", "name": "Gilead Sciences"},
        {"ticker": "BMY", "name": "Bristol-Myers Squibb"}
    ],
    "Energy & Oil": [
        {"ticker": "XOM", "name": "Exxon Mobil"},
        {"ticker": "CVX", "name": "Chevron Corp."},
        {"ticker": "SHEL", "name": "Shell plc"},
        {"ticker": "TTE", "name": "TotalEnergies"},
        {"ticker": "COP", "name": "ConocoPhillips"},
        {"ticker": "BP", "name": "BP plc"},
        {"ticker": "PBR", "name": "Petrobras"},
        {"ticker": "EOG", "name": "EOG Resources"},
        {"ticker": "SLB", "name": "Schlumberger"},
        {"ticker": "MPC", "name": "Marathon Petroleum"},
        {"ticker": "PSX", "name": "Phillips 66"},
        {"ticker": "VLO", "name": "Valero Energy"},
        {"ticker": "OXY", "name": "Occidental Petroleum"},
        {"ticker": "KMI", "name": "Kinder Morgan"},
        {"ticker": "WMB", "name": "Williams Companies"}
    ],
    "Consumer & Retail": [
        {"ticker": "AMZN", "name": "Amazon.com"},
        {"ticker": "WMT", "name": "Walmart"},
        {"ticker": "PG", "name": "Procter & Gamble"},
        {"ticker": "HD", "name": "Home Depot"},
        {"ticker": "COST", "name": "Costco"},
        {"ticker": "KO", "name": "Coca-Cola"},
        {"ticker": "PEP", "name": "PepsiCo"},
        {"ticker": "MCD", "name": "McDonald's"},
        {"ticker": "NKE", "name": "Nike"},
        {"ticker": "SBUX", "name": "Starbucks"},
        {"ticker": "TGT", "name": "Target"},
        {"ticker": "LOW", "name": "Lowe's"},
        {"ticker": "TJX", "name": "TJX Companies"},
        {"ticker": "EL", "name": "Estee Lauder"},
        {"ticker": "CL", "name": "Colgate-Palmolive"}
    ]
}

def get_market_names():
    return list(MARKETS.keys())

def get_stocks_for_market(market_name):
    return MARKETS.get(market_name, [])

def search_sector(query):
    """
    Simple keyword search to map user queries to sectors.
    """
    query = query.lower().strip()
    
    # Keywords mapping
    keywords = {
        "car": "Automotive (Cars)",
        "auto": "Automotive (Cars)",
        "vehicle": "Automotive (Cars)",
        "tech": "Technology",
        "software": "Technology",
        "computer": "Technology",
        "chip": "Technology",
        "bank": "Finance & Banking",
        "finance": "Finance & Banking",
        "money": "Finance & Banking",
        "health": "Healthcare & Pharma",
        "pharma": "Healthcare & Pharma",
        "drug": "Healthcare & Pharma",
        "med": "Healthcare & Pharma",
        "oil": "Energy & Oil",
        "gas": "Energy & Oil",
        "energy": "Energy & Oil",
        "retail": "Consumer & Retail",
        "shop": "Consumer & Retail",
        "store": "Consumer & Retail",
        "food": "Consumer & Retail"
    }
    
    # Check for direct key match
    for sector in SECTORS.keys():
        if query in sector.lower():
            return SECTORS[sector]
            
    # Check keywords
    for key, sector_name in keywords.items():
        if key in query:
            return SECTORS[sector_name]
            
    return []

def get_sector_names():
    return list(SECTORS.keys())
